version: '2'
services:
    testproject-app:
        image: testproject
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testproject-postgresql:5432/testproject
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testproject-postgresql:
        extends:
            file: postgresql.yml
            service: testproject-postgresql
